- name: Add packages for password
  set_fact:
    default_packages: "{{ default_packages + [ 'gnome-keyring' ] }}"

- name: Add packages for authentication
  set_fact:
    default_packages: "{{ default_packages + [ 'lxpolkit' ] }}"

- name: Add packages for development
  set_fact:
    default_packages: >
      {{ default_packages
        + [ 'bat', 'fzf', 'jq', 'shellcheck', 'watchman', 'unzip' ] }}

- name: Add packages for development (build)
  set_fact:
    default_packages: >
      {{ default_packages
        + [ 'make', 'build-essential', 'libssl-dev', 'zlib1g-dev', 'libbz2-dev',
            'libreadline-dev', 'libsqlite3-dev', 'wget', 'curl', 'llvm',
            'libncurses5-dev', 'xz-utils', 'tk-dev', 'libxml2-dev',
            'libxmlsec1-dev', 'libxmlsec1-dev', 'libffi-dev', 'liblzma-dev',
            'default-libmysqlclient-dev', 'libpq-dev', 'libcurl4-gnutls-dev' ] }}

- name: Add packages for development (python)
  set_fact:
    default_packages: >
      {{ default_packages
        + [ 'python3', 'python3-apt', 'python3-venv', 'python3-dev' ] }}

- name: Prepare dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config/bat
    - ~/.config/bpython
    - ~/.config/pip
    - ~/.config/pypoetry

- name: Link configurations
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files/bat/config', path: '~/.config/bat/config' }
    - { src: 'files/bpython/base16.theme', path: '~/.config/bpython/base16.theme' }
    - { src: 'files/bpython/config', path: '~/.config/bpython/config' }
    - { src: 'files/pip/pip.conf', path: '~/.config/pip/pip.conf' }
    - { src: 'files/poetry/config.toml', path: '~/.config/pypoetry/config.toml' }
