#!/bin/bash

update_chrome_exec() {
  # edit Exec options (overlay scroll bar, dark mode, etc)
  if [ -f /usr/share/applications/google-chrome.desktop ]; then
    local skip_pattern=".*dark-mode.*"
    local search_pattern="^Exec.*$"

    local flags="--enable-features=WebUIDarkMode,OverlayScrollbar"
    local dark_mode="--force-dark-mode"
    local replace_pattern="& $flags $dark_mode"

    sudo sed -i.bak "/$skip_pattern/b; s/$search_pattern/$replace_pattern/g" \
      /usr/share/applications/google-chrome.desktop

    sudo rm -r /usr/share/applications/google-chrome.desktop.bak
    echo "chrome exec was updated."
  fi
}

update_chrome_exec
