#!/bin/bash

update_exec() {
  # edit Exec options (overlay scroll bar, dark mode, etc)
  local skip_pattern=".*dark-mode.*"
  local search_pattern="^Exec.*$"

  local flags="--enable-features=WebUIDarkMode,OverlayScrollbar"
  local dark_mode="--force-dark-mode"
  local hard_acc="--enable-accelerated-video-decode"

  # chrome
  if [ -f /usr/share/applications/google-chrome.desktop ]; then
    local replace_pattern="& $flags $dark_mode $hard_acc"

    sudo sed -i -Ee "/$skip_pattern/b; s/$search_pattern/$replace_pattern/g" \
      /usr/share/applications/google-chrome.desktop

    echo "chrome exec was updated."
  fi

  # slack
  if [ -f /usr/share/applications/slack.desktop ]; then
    local replace_pattern="& $flags $dark_mode"

    sudo sed -i -Ee "/$skip_pattern/b; s/$search_pattern/$replace_pattern/g" \
      /usr/share/applications/slack.desktop

    echo "slack exec was updated."
  fi
}

update_exec
unset -f update_exec
