#!/bin/bash

update_vscodium_setting() {
  # Installed vscodium, jq exists
  if [ -f /usr/share/codium/resources/app/product.json ] && \
     [ "$(command -v jq)" ]
  then
    # create bak file
    sudo cp /usr/share/codium/resources/app/product.json \
      /usr/share/codium/resources/app/product.json.bak

    # edit json and write
    jq < /usr/share/codium/resources/app/product.json.bak \
      ".extensionAllowedProposedApi |= . +
      [\"ms-python.python\"]" \
    | jq ".extensionAllowedProposedApi |= unique" \
    | sudo tee >/dev/null /usr/share/codium/resources/app/product.json

    # shellcheck disable=SC2002
    cat /usr/share/codium/resources/app/product.json.bak \
      | jq ".extensionsGallery.serviceUrl = \
        \"https://marketplace.visualstudio.com/_apis/public/gallery\"" \
      | jq ".extensionsGallery.cacheUrl = \
        \"https://vscode.blob.core.windows.net/gallery/index\"" \
      | jq ".extensionsGallery.itemUrl = \
        \"https://marketplace.visualstudio.com/items\"" \
      | sudo tee >/dev/null /usr/share/codium/resources/app/product.json

    echo "vscodim setting was updated."
  fi
}

update_vscodium_setting
