- name: Add scripts
  set_fact:
    default_user_scripts: >
      {{ default_user_scripts
        + [ 'gsettings set org.gnome.desktop.interface font-name "Pretendard 10"',
            'gsettings set org.gnome.desktop.interface document-font-name "Pretendard 10"',
            'gsettings set org.gnome.desktop.wm.preferences titlebar-font "Pretendard Semibold 10"',
            'gsettings set org.gnome.desktop.interface monospace-font-name "FiraMono Nerd Font Mono 10"' ] }}

- name: Prepare dirs
  file:
    path: ~/.config/fontconfig
    state: directory

- name: Link configurations
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files/fonts.conf', path: '~/.config/fontconfig/fonts.conf' }
