- name: Add apt signing key
  become: true
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc99b11deb97541f0

- name: Add apt repository
  become: true
  apt_repository:
    repo: deb https://cli.github.com/packages stable main
    filename: github-cli

- name: Add packages
  set_fact:
    default_packages: "{{ default_packages + [ 'gh' ] }}"

- name: Template configuration
  template:
    src: templates/hosts.yml
    dest: "{{ role_path }}/files.private/hosts.yml"

- name: Link configurations
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files/config.yml', path: '~/.config/gh/config.yml' }
    - { src: 'files.private/hosts.yml', path: '~/.config/gh/hosts.yml' }
