- name: Get dpkg architecture
  command: dpkg --print-architecture
  check_mode: false
  changed_when: false
  register: dpkg_architecture_output

- name: Prepare facts
  set_fact:
    default_architecture: "{{ dpkg_architecture_output.stdout }}"
    default_packages: []

- name: Prepare dirs
  file:
    path: ~/.local/share/applications
    state: directory

- name: Install requirements
  become: true
  apt:
    name:
      - gpg
    update_cache: true
    install_recommends: false
  when: not ansible_check_mode

- name: Uninstall bloats
  become: true
  apt:
    name:
      - cloud-init
    state: absent
    purge: true
    install_recommends: false
  when: not ansible_check_mode
