- name: Get dpkg architecture
  command: dpkg --print-architecture
  check_mode: false
  changed_when: false
  register: dpkg_architecture_output

- name: Gather package facts
  package_facts:
    manager: apt

- name: Prepare facts
  set_fact:
    default_architecture: "{{ dpkg_architecture_output.stdout }}"
    default_packages: []
    default_scripts: []
    default_user_scripts: []

- name: Prepare dirs
  file:
    path: ~/.local/share/applications
    state: directory

- name: Install requirements
  become: true
  vars:
    packages: [dirmngr, git, gpg, gpg-agent, lsb-release, openssh-client]
  apt:
    name: "{{ packages }}"
    update_cache: true
    install_recommends: false
  when: ansible_facts.packages | intersect(packages) | length != packages | length

- name: Uninstall bloats
  become: true
  apt:
    name:
      - cloud-init
    state: absent
    purge: true
    install_recommends: false
  when: not ansible_check_mode
