- name: Add packages
  set_fact:
    default_packages: "{{ default_packages + [ 'maim', 'xorg' ] }}"

- name: Prepare dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/default
    - /etc/X11/xinit

- name: Link configurations (sudo)
  become: true
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files/keyboard', path: '/etc/default/keyboard' }
    - { src: 'files/xserverrc', path: '/etc/X11/xinit/xserverrc' }
