- name: Install bins
  git:
    repo: git@github.com:sudosubin/bins.git
    dest: "{{ ansible_env.HOME }}/Code/sudosubin/bins"

- name: Add packages, scripts
  set_fact:
    default_user_scripts: >
      {{ default_user_scripts
        + [ 'make -f {{ ansible_env.HOME }}/Code/sudosubin/bins/Makefile prepare' ]
        + [ 'make -f {{ ansible_env.HOME }}/Code/sudosubin/bins/Makefile install' ] }}
