- name: Install bins
  git:
    repo: git@github.com:sudosubin/bins.git
    dest: "~/Code/sudosubin/bins"

- name: Template configuration
  no_log: true
  template:
    src: templates/.makerc.j2
    dest: "~/Code/sudosubin/bins/.makerc"

- name: Add packages, scripts
  set_fact:
    default_user_scripts: >
      {{ default_user_scripts
        + [ 'make -f ~/Code/sudosubin/bins/Makefile prepare',
            'make -f ~/Code/sudosubin/bins/Makefile install' ] }}
