- name: Template configurations
  no_log: true
  template:
    src: "{{ item.src }}"
    dest: "{{ role_path }}/{{ item.dest }}"
  loop:
    - { src: 'templates/.npmrc.j2', dest: 'files.private/.npmrc' }

- name: Link configurations
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files.private/.npmrc', path: '~/.npmrc' }
