- name: Add apt signing key
  become: true
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg

- name: Add apt repository
  become: true
  apt_repository:
    repo: deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main
    filename: vscodium

- name: Add packages
  set_fact:
    default_packages: "{{ default_packages + [ 'codium' ] }}"

- name: Link configurations
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files/settings.json', path: '~/.config/VSCodium/User/settings.json' }
    - { src: 'files/snippets/typescript.json', path: '~/.config/VSCodium/User/snippets/typescript.json' }
    - { src: 'files/snippets/typescriptreact.json', path: '~/.config/VSCodium/User/snippets/typescriptreact.json' }
