- name: Prepare dirs
  file:
    path: ~/.ssh
    state: directory

- name: Template configurations
  no_log: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0600"
  loop:
    - { src: 'templates/id_ed25519.j2', dest: '~/.ssh/id_ed25519' }
    - { src: 'templates/id_ed25519.pub.j2', dest: '~/.ssh/id_ed25519.pub' }

- name: Add ssh key
  shell: >
    eval "$(ssh-agent)";
    ssh-add ~/.ssh/id_ed25519;
    eval "$(ssh-agent -k)";

- name: Link configurations
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files/config', path: '~/.ssh/config' }
