- name: Set system timezone
  become: true
  shell: timedatectl set-timezone Asia/Seoul

- name: Template configuration
  template:
    src: templates/override.conf
    dest: "{{ role_path }}/files.private/override.conf"

- name: Link configurations
  become: true
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files.private/override.conf', path: '/etc/systemd/system/getty@tty1.service.d/override.conf' }  # Enable auto-login
