- name: Set system timezone
  become: true
  shell: timedatectl set-timezone Asia/Seoul

- name: Add packages, scripts
  set_fact:
    default_packages: "{{ default_packages + [ 'resolvconf', 'openvpn' ] }}"
    default_scripts: >
      {{ default_scripts
        + [ 'resolvconf -u' ]
        + [ 'service resolvconf restart' ] }}

- name: Template configuration
  template:
    src: templates/override.conf
    dest: "{{ role_path }}/files.private/override.conf"

- name: Link configurations
  become: true
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files/sysctl.conf', path: '/etc/sysctl.conf' }  # Change max fs watch
    - { src: 'files/tail', path: '/etc/resolvconf/resolv.conf.d/tail' }  # Enable dns
    - { src: 'files.private/override.conf', path: '/etc/systemd/system/getty@tty1.service.d/override.conf' }  # Enable auto-login
