- name: Prepare dirs
  file:
    path: ~/.config/git
    state: directory

- name: Link configurations
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files/.gitconfig', path: '~/.gitconfig' }
    - { src: 'files/ignore', path: '~/.config/git/ignore' }
