- name: Add apt signing key
  become: true
  apt_key:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey

- name: Add apt repository
  become: true
  apt_repository:
    repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
    filename: slack

- name: Add packages
  set_fact:
    default_packages: "{{ default_packages + [ 'slack-desktop' ] }}"

- name: Link configurations
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files/slack.desktop', path: '~/.local/share/applications/slack.desktop' }
