- name: Check installed alacritty version
  shell: "dpkg-query --showformat='${Version}' --show alacritty || echo '0.0.0'"
  check_mode: false
  changed_when: false
  register: version_output

- name: Check latest GitHub release
  uri:
    url: https://api.github.com/repos/barnumbirr/alacritty-debian/releases/latest
    return_content: true
  check_mode: false
  register: release_output

- name: Prepare facts
  set_fact:
    installed_version: "v{{ version_output.stdout }}"
    latest_version: "{{ release_output.json.tag_name }}"
    distribution_name: >-
      {{ ansible_facts['distribution_release'] if ansible_facts['distribution_release'] in ['buster', 'testing', 'unstable'] else 'unstable' }}

- name: Download and install alacritty
  block:
    - name: Download and Install alacritty {{ latest_version }}
      become: true
      apt:
        deb: "{{ item.browser_download_url }}"
      loop: "{{ release_output.json.assets }}"
      loop_control:
        label: "{{ item.name }}"
      when: "distribution_name + '.deb' in item.name"

    - name: Set default terminal as alacritty
      become: true
      shell: "update-alternatives --set x-terminal-emulator $(which alacritty)"

  when: "installed_version != latest_version"

- name: Link configurations
  loop:
    - { src: 'files/alacritty.yml', path: '~/.config/alacritty/alacritty.yml' }
  file:
    src: "{{ role_path + '/' + item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
