- name: Add packages, scripts
  set_fact:
    default_packages: "{{ default_packages + [ 'openvpn' ] }}"
    default_scripts: >
      {{ default_scripts
        + [ 'resolvconf -u' ]
        + [ 'service resolvconf restart' ] }}

- name: Prepare dirs
  file:
    path: /etc/resolvconf/resolv.conf.d
    state: directory

- name: Link configurations
  become: true
  file:
    src: "{{ role_path }}/{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    force: true
  loop:
    - { src: 'files/tail', path: '/etc/resolvconf/resolv.conf.d/tail' }  # Enable dns
