name: Test

on: [pull_request, push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
            extra_nix_config: |
              experimental-features = nix-command flakes
      - run: nix flake check
