name: Test

on: [pull_request, push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - run: |
          nix-shell \
            -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/5efc8ca954272c4376ac929f4c5ffefcc20551d5.tar.gz \
            -p nixpkgs-fmt \
            --run 'nixpkgs-fmt .'
